"""empty message

Revision ID: 25536509ad5f
Revises: c27e3f0b0cbf
Create Date: 2019-10-16 14:14:15.423000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25536509ad5f'
down_revision = 'c27e3f0b0cbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password2', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password2')
    # ### end Alembic commands ###
