"""empty message

Revision ID: 3e705d1a765c
Revises: 25536509ad5f
Create Date: 2019-10-16 14:14:54.633000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3e705d1a765c'
down_revision = '25536509ad5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password2', mysql.VARCHAR(length=100), nullable=False))
    # ### end Alembic commands ###
